__author__ = 'Zhibekchach Myrzaeva'


#utility function written using openpyx1

def r_count (file, sheetName):...

def c_count(file, sheetName):...

def readData(file, sheetName, rowNum, columnNum): ...

def writtenData (file, sheetName, rowNum, columnNum):...

# utility function written using pandas:

def getData(path, sheetName):...

def updateResult (path, sheetName, columnName, passResult, rowNum, color):...

def updateExecution(path, sheetName, rowNum):...
